In [1]:
# 数组的拼接于分裂
import numpy as np 

In [2]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [3]:
x + y

array([4, 4, 4])

In [4]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [5]:
z = np.array([99,99,99])
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [6]:
grid = np.array([
    [1,2,3],
    [4,5,6]
])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.concatenate([grid,grid],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [10]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [11]:
# 垂直栈
x = np.array([1,2,3])
grid = np.arange(1,7).reshape((2,3))

In [12]:
x

array([1, 2, 3])

In [13]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# 垂直栈
np.vstack([grid,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [22]:
x = np.array([99,99])[:,np.newaxis]
x

array([[99],
       [99]])

In [23]:
# 水平栈
np.hstack([grid,x])


array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [24]:
# 数据分裂
x = np.array([1,2,3,4,5,6,7,8])
x1,x2,x3,x4 = np.split(x,[2,4,6])
x1

array([1, 2])

In [25]:
x2

array([3, 4])

In [26]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
# 垂直栈
uper,lower = np.vsplit(grid,[2])
uper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
# 水平栈
left,right = np.hsplit(grid,[2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])