In [1]:
# NumPy 数组的属性
import numpy as np

In [16]:
np.random.seed(0)  # 设置随机数种子

x1 = np.random.randint(10,size=6)  # 长度为6的一维数组
x2 = np.random.randint(10,size=(3,4)) # 3 * 4 二维数组
x3 = np.random.randint(10,size=(2,3,3)) # 三维数组

In [13]:
x1

array([5, 0, 3, 3, 7, 9])

In [14]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [17]:
x3

array([[[8, 1, 5],
        [9, 8, 9],
        [4, 3, 0]],

       [[3, 5, 0],
        [2, 3, 8],
        [1, 3, 3]]])

In [19]:
x1.ndim

1

In [20]:
x2.ndim

2

In [21]:
x3.ndim  #  ndim 表示数组的维度

3

In [24]:
# 数组的形状（每一个维度的大小）
x1.shape

(6,)

In [27]:
# 数组个数的总的大小
x3.size   

18

In [30]:
# 查看数据类型
x2.dtype

dtype('int32')

In [31]:
# 数组的索引
x1

array([5, 0, 3, 3, 7, 9])

In [32]:
x1[2]

3

In [33]:
x1[-2]

7

In [34]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
x2[0,1]

5

In [36]:
x2[1,2]

8

In [37]:
x2[0,0] = 33
x2

array([[33,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])